### ISSUE TITLE
Add Ambassadors' Locations to the Landing Page

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/ambassadors#4]
After discussing with the FINOS team, we thought it would be helpful to include each ambassador's location on the [Ambassador landing page](https://www.finos.org/ambassador-program#how_to_get_involved).

**Action Needed:**
Ambassadors, please confirm if you are okay with including your city by giving this issue a 👍 reaction.

**Note:**
If you have any concerns or would like to discuss further, feel free to comment below.

**Comment by sammoorhouse** [comment]
Brooklyn, NY

**Comment by psmulovics** [comment]
@psmulovics - Long Island, New York or 'Greater New York Area' based on how others will define

**Comment by opoupeney** [comment]
Greater New York Area (to be consistent with Peter)

**Comment by TheHaymaker** [comment]
Chicago,  IL

**Comment by eddie-knight** [comment]
Austin, Texas

**Comment by vinod-goje** [comment]
Greater New York Area

**Comment by BrittanyIstenes** [comment]
Brittany Istenes - Northeast Ohio - Cleveland
